<?php

namespace Tests\Feature;

use App\Models\Reply;
use App\Models\Thread;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class ThreadsReadTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = Thread::factory()->create();
    }

    /**
     * @test
     */
    public function a_user_can_see_all_threads(): void
    {
        $response = $this->get("/threads");
        $response->assertStatus(200);
        $response->assertSee($this->thread->title);
    }

    /**
     * @return void
     * @test
     */
    public function a_user_can_see_single_thread()
    {
        $response = $this->get("/threads/" . $this->thread->id);
        $response->assertStatus(200);
        $response->assertSee($this->thread->title);
    }

    /**
     * @return void
     * @test
     */
    public function a_user_can_see_replies_of_thread()
    {
        $replay = Reply::factory()->for($this->thread)->create();
        $response = $this->get("/threads/" . $this->thread->id);
        $response->assertSee($replay->body);
    }

    /**
     * @return void
     * @test
     */
    public function a_user_can_see_reply_owner_name()
    {
        $replay = Reply::factory()->for($this->thread)->create();
        $response = $this->get("/threads/" . $this->thread->id);
        $response->assertSee($replay->owner->name);
    }
}
